# Generated by Django 4.0.4 on 2022-04-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_habilidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='habilidad',
            field=models.ManyToManyField(to='persona.habilidades'),
        ),
    ]
