# Generated by Django 4.0.4 on 2022-04-21 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0005_estudiante_habilidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudiante',
            options={'ordering': ['apellido', 'primernombre'], 'verbose_name': 'Estudiante', 'verbose_name_plural': 'Estudiantes matriculados'},
        ),
    ]
