# Generated by Django 4.0.4 on 2022-04-21 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0006_alter_estudiante_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='nombreCompleto',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre Completo'),
        ),
    ]
