# Generated by Django 2.2.3 on 2022-04-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('nombreCorto', models.CharField(blank=True, max_length=10, unique=True, verbose_name='NombreCorto')),
                ('activo', models.BooleanField(default=True, verbose_name='FacultadActiva')),
            ],
        ),
    ]
